export const mockStudents = [
  {
    id: "1",
    name: "Ahmad Rizki",
    studentId: "STU-001",
    email: "ahmad@example.com",
    status: "active" as const,
    reportsSubmitted: 3,
    totalReports: 4,
    averageScore: 8.5,
    department: "Information Technology",
    mentorId: "MEN-001",
    startDate: "2024-01-01",
    endDate: "2024-03-31",
  },
  {
    id: "2",
    name: "Siti Nurhaliza",
    studentId: "STU-002",
    email: "siti@example.com",
    status: "active" as const,
    reportsSubmitted: 4,
    totalReports: 4,
    averageScore: 9.0,
    department: "Information Technology",
    mentorId: "MEN-001",
    startDate: "2024-01-01",
    endDate: "2024-03-31",
  },
  {
    id: "3",
    name: "Budi Santoso",
    studentId: "STU-003",
    email: "budi@example.com",
    status: "active" as const,
    reportsSubmitted: 2,
    totalReports: 4,
    averageScore: 7.8,
    department: "Information Technology",
    mentorId: "MEN-002",
    startDate: "2024-01-01",
    endDate: "2024-03-31",
  },
]

// Mock Mentors
export const mockMentors = [
  {
    id: "MEN-001",
    name: "Budi Santoso",
    mentorId: "MEN-001",
    email: "budi.mentor@example.com",
    status: "active" as const,
    studentsCount: 3,
    department: "Information Technology",
    joinDate: "2023-06-01",
  },
  {
    id: "MEN-002",
    name: "Siti Nurhaliza",
    mentorId: "MEN-002",
    email: "siti.mentor@example.com",
    status: "active" as const,
    studentsCount: 4,
    department: "Information Technology",
    joinDate: "2023-07-15",
  },
  {
    id: "MEN-003",
    name: "Ahmad Rizki",
    mentorId: "MEN-003",
    email: "ahmad.mentor@example.com",
    status: "inactive" as const,
    studentsCount: 0,
    department: "Information Technology",
    joinDate: "2023-08-20",
  },
]

// Mock Reports
export const mockReports = [
  {
    id: "1",
    studentId: "1",
    week: "Minggu 1",
    date: "2024-01-08",
    status: "submitted" as const,
    title: "Penyiapan Awal & Orientasi",
    activities:
      "Minggu ini saya menyelesaikan proses onboarding, menyiapkan lingkungan pengembangan, dan mengikuti sesi orientasi.",
    challenges:
      "Awalnya ada beberapa kendala saat penyiapan lingkungan, tetapi tim TI membantu menyelesaikannya dengan cepat.",
    nextWeek: "Minggu depan saya berencana mulai mengerjakan desain skema basis data.",
    feedback: "Awal yang bagus! Penyiapan sudah lengkap dan siap memulai pekerjaan pengembangan.",
    score: 8.5,
  },
  {
    id: "2",
    studentId: "1",
    week: "Minggu 2",
    date: "2024-01-15",
    status: "submitted" as const,
    title: "Perancangan & Implementasi Basis Data",
    activities: "Merancang skema basis data dan mengimplementasikan tabel awal.",
    challenges: "Melakukan optimasi beberapa kueri agar kinerja lebih baik.",
    nextWeek: "Mulai pengembangan API.",
    feedback: "Perancangan basis data sangat baik! Pertahankan kinerjanya.",
    score: 8.7,
  },
  {
    id: "3",
    studentId: "1",
    week: "Minggu 3",
    date: "2024-01-22",
    status: "submitted" as const,
    title: "Pengembangan API",
    activities: "Mengembangkan endpoint REST API untuk fitur inti.",
    challenges: "Implementasi autentikasi memakan waktu lebih lama dari perkiraan.",
    nextWeek: "Menuntaskan pengujian API dan dokumentasi.",
    feedback: "Progres yang baik pada pengembangan API.",
    score: 8.3,
  },
  {
    id: "4",
    studentId: "1",
    week: "Minggu 4",
    date: "2024-01-29",
    status: "pending" as const,
    title: "Pengujian & Debugging",
    activities: "Menerapkan rangkaian pengujian yang komprehensif.",
    challenges: "Menemukan dan memperbaiki beberapa kasus tepi.",
    nextWeek: "Deploy ke lingkungan staging.",
    feedback: null,
    score: null,
  },
  // Additional items for richer list
  {
    id: "5",
    studentId: "2",
    week: "Minggu 1",
    date: "2024-01-08",
    status: "submitted" as const,
    title: "Orientasi & Penyiapan",
    activities: "Menyelesaikan orientasi dan penyiapan lingkungan kerja.",
    challenges: "Masalah konfigurasi kecil berhasil diatasi.",
    nextWeek: "Mulai riset modul.",
    feedback: "Momentum yang baik sejak awal.",
    score: 9.0,
  },
  {
    id: "6",
    studentId: "2",
    week: "Minggu 2",
    date: "2024-01-15",
    status: "submitted" as const,
    title: "Riset Modul & Desain",
    activities: "Meneliti alternatif dan mengajukan rancangan.",
    challenges: "Melakukan spike terukur agar tidak melebar.",
    nextWeek: "Mulai implementasi.",
    feedback: "Alasan desain yang kuat.",
    score: 9.2,
  },
  {
    id: "7",
    studentId: "2",
    week: "Minggu 3",
    date: "2024-01-22",
    status: "submitted" as const,
    title: "Implementasi Tahap 1",
    activities: "Mengimplementasikan komponen inti dan pengujian.",
    challenges: "Menangani kasus tepi pada validasi.",
    nextWeek: "Integrasi dengan API.",
    feedback: "Cakupan pengujian yang sangat baik.",
    score: 9.1,
  },
  {
    id: "8",
    studentId: "3",
    week: "Minggu 1",
    date: "2024-01-08",
    status: "submitted" as const,
    title: "Orientasi & Peralatan",
    activities: "Mengeksplorasi perangkat dan penyiapan proyek.",
    challenges: "Ada kurva belajar pada penggunaan alat.",
    nextWeek: "Menyusun draf skema awal.",
    feedback: "Inisiatif yang baik.",
    score: 7.9,
  },
  {
    id: "9",
    studentId: "3",
    week: "Minggu 2",
    date: "2024-01-15",
    status: "submitted" as const,
    title: "Draf Skema & Tinjauan",
    activities: "Menyusun draf skema dan meninjau bersama mentor.",
    challenges: "Disempurnakan untuk kinerja.",
    nextWeek: "Mengimplementasikan migrasi.",
    feedback: "Perbaikan terlihat.",
    score: 8.0,
  },
  {
    id: "10",
    studentId: "3",
    week: "Minggu 3",
    date: "2024-01-22",
    status: "pending" as const,
    title: "Migrasi & Seeding",
    activities: "Mengerjakan migrasi dan data awal (seed).",
    challenges: "Menunggu tinjauan terkait constraint.",
    nextWeek: "Finalisasi dan pengujian.",
    feedback: null,
    score: null,
  },
]

// Mock Evaluations
export const mockEvaluations = [
  {
    id: "1",
    studentId: "1",
    mentorId: "MEN-001",
    date: "2024-01-15",
    type: "Mid-week Check-in",
    score: 8.5,
    feedback: "Good progress on database design. Keep up the good work!",
  },
  {
    id: "2",
    studentId: "2",
    mentorId: "MEN-001",
    date: "2024-01-16",
    type: "Weekly Review",
    score: 9.0,
    feedback: "Excellent work on API implementation.",
  },
  {
    id: "3",
    studentId: "3",
    mentorId: "MEN-002",
    date: "2024-01-17",
    type: "Progress Check",
    score: 7.8,
    feedback: "Needs improvement on documentation.",
  },
]

// Mock Analytics Data
export const mockAnalytics = {
  totalStudents: 156,
  totalMentors: 24,
  reportsSubmitted: 487,
  completionRate: 92,
  averageScore: 8.2,
  reportSubmissionData: [
    { week: "Week 1", submitted: 156, pending: 0 },
    { week: "Week 2", submitted: 152, pending: 4 },
    { week: "Week 3", submitted: 148, pending: 8 },
    { week: "Week 4", submitted: 145, pending: 11 },
  ],
  scoreDistribution: [
    { name: "9-10", value: 45 },
    { name: "8-9", value: 78 },
    { name: "7-8", value: 25 },
    { name: "Below 7", value: 8 },
  ],
  departmentStats: [
    { department: "IT", students: 45, mentors: 8 },
    { department: "Engineering", students: 38, mentors: 6 },
    { department: "Business", students: 42, mentors: 7 },
    { department: "Design", students: 31, mentors: 5 },
  ],
}

// Mock Attendance (one record per student per date when present)
export const mockAttendance = [
  // 2024-01-08
  { id: "att-2024-01-08-1", date: "2024-01-08", studentId: "1", status: "present" as const },
  { id: "att-2024-01-08-2", date: "2024-01-08", studentId: "2", status: "present" as const },
  // 2024-01-09
  { id: "att-2024-01-09-1", date: "2024-01-09", studentId: "1", status: "present" as const },
  { id: "att-2024-01-09-3", date: "2024-01-09", studentId: "3", status: "present" as const },
  // 2024-01-15
  { id: "att-2024-01-15-2", date: "2024-01-15", studentId: "2", status: "present" as const },
  { id: "att-2024-01-15-3", date: "2024-01-15", studentId: "3", status: "present" as const },
]
