CREATE TYPE "public"."attendance_status" AS ENUM('present', 'absent', 'late', 'excused');--> statement-breakpoint
CREATE TYPE "public"."competency_category" AS ENUM('personality', 'technical');--> statement-breakpoint
CREATE TYPE "public"."event_type" AS ENUM('meeting', 'deadline', 'milestone', 'in_class', 'field_trip', 'meet_greet');--> statement-breakpoint
CREATE TYPE "public"."notification_type" AS ENUM('assignment', 'approval', 'reminder', 'system');--> statement-breakpoint
CREATE TYPE "public"."owner_type" AS ENUM('task', 'report', 'final_report', 'assessment', 'calendar_event', 'attendance_log');--> statement-breakpoint
CREATE TYPE "public"."placement_status" AS ENUM('active', 'completed', 'canceled');--> statement-breakpoint
CREATE TYPE "public"."report_type" AS ENUM('daily', 'weekly', 'monthly');--> statement-breakpoint
CREATE TYPE "public"."review_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."task_status" AS ENUM('todo', 'in_progress', 'submitted', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'mentor', 'student');--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assessment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assessment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"placementId" integer NOT NULL,
	"evaluatorMentorId" integer,
	"comments" text,
	"totalScore" numeric(5, 2),
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assessment_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assessment_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assessmentId" integer NOT NULL,
	"criterion" text NOT NULL,
	"maxScore" numeric(5, 2),
	"score" numeric(5, 2),
	"comments" text,
	"position" integer
);
--> statement-breakpoint
CREATE TABLE "attachment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attachment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_type" "owner_type" NOT NULL,
	"ownerId" integer NOT NULL,
	"url" text NOT NULL,
	"filename" text,
	"mimeType" text,
	"sizeBytes" integer,
	"createdById" varchar(255),
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "attendance_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attendance_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"placementId" integer NOT NULL,
	"date" date NOT NULL,
	"checkInAt" timestamp with time zone,
	"checkOutAt" timestamp with time zone,
	"status" "attendance_status" DEFAULT 'present' NOT NULL,
	"latitude" numeric(9, 6),
	"longitude" numeric(9, 6),
	"locationNote" text,
	"verifiedByMentorId" integer,
	"verifiedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "calendar_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "calendar_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"placementId" integer,
	"type" "event_type" NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"scheduledAt" timestamp with time zone NOT NULL,
	"endDate" timestamp with time zone,
	"location" text,
	"organizerName" text,
	"organizerLogoUrl" text,
	"colorHex" varchar(16),
	"createdById" varchar(255),
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "company_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"address" text,
	"latitude" numeric(9, 6),
	"longitude" numeric(9, 6),
	"contactEmail" text,
	"contactPhone" varchar(30),
	"website" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "competency_template" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "competency_template_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"category" "competency_category" NOT NULL,
	"major" text NOT NULL,
	"weight" numeric(5, 2),
	"position" integer,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "final_report" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "final_report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"placementId" integer NOT NULL,
	"title" text,
	"content" text,
	"submittedAt" timestamp with time zone,
	"approvedByMentorId" integer,
	"approvedAt" timestamp with time zone,
	"grade" text,
	"totalScore" numeric(10, 2),
	"averageScore" numeric(5, 2),
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "final_report_score" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "final_report_score_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"finalReportId" integer NOT NULL,
	"competencyTemplateId" integer NOT NULL,
	"score" numeric(5, 2)
);
--> statement-breakpoint
CREATE TABLE "mentor_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mentor_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"companyId" integer,
	"phone" varchar(30),
	"active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"type" "notification_type" NOT NULL,
	"title" text NOT NULL,
	"body" text,
	"isRead" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "placement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "placement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"studentId" integer NOT NULL,
	"mentorId" integer NOT NULL,
	"companyId" integer NOT NULL,
	"programId" integer,
	"startDate" date,
	"endDate" date,
	"status" "placement_status" DEFAULT 'active' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "program" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "program_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text,
	"startDate" date,
	"endDate" date,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "report" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "report_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"placementId" integer NOT NULL,
	"type" "report_type" NOT NULL,
	"title" text,
	"content" text,
	"periodStart" date,
	"periodEnd" date,
	"submittedAt" timestamp with time zone,
	"reviewedByMentorId" integer,
	"review_status" "review_status" DEFAULT 'pending' NOT NULL,
	"reviewNotes" text,
	"reviewedAt" timestamp with time zone,
	"score" numeric(5, 2),
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"impersonated_by" text,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "student_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"nis" text,
	"birthPlace" text,
	"birthDate" date,
	"gender" text,
	"semester" integer,
	"school" text,
	"major" text,
	"cohort" text,
	"address" text,
	"phone" varchar(30),
	"active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"placementId" integer NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"dueDate" date,
	"status" "task_status" DEFAULT 'todo' NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"submissionNote" text,
	"submittedAt" timestamp with time zone,
	"score" integer,
	"reviewNotes" text,
	"targetMajor" text
);
--> statement-breakpoint
CREATE TABLE "task_checklist_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_checklist_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taskId" integer NOT NULL,
	"label" text NOT NULL,
	"isCompleted" boolean DEFAULT false NOT NULL,
	"position" integer
);
--> statement-breakpoint
CREATE TABLE "task_competency_impact" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_competency_impact_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"taskId" integer NOT NULL,
	"competencyTemplateId" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"role" "user_role" DEFAULT 'student' NOT NULL,
	"banned" boolean DEFAULT false NOT NULL,
	"ban_reason" text,
	"ban_expires" timestamp,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assessment" ADD CONSTRAINT "assessment_placementId_placement_id_fk" FOREIGN KEY ("placementId") REFERENCES "public"."placement"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assessment" ADD CONSTRAINT "assessment_evaluatorMentorId_mentor_profile_id_fk" FOREIGN KEY ("evaluatorMentorId") REFERENCES "public"."mentor_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assessment_item" ADD CONSTRAINT "assessment_item_assessmentId_assessment_id_fk" FOREIGN KEY ("assessmentId") REFERENCES "public"."assessment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attachment" ADD CONSTRAINT "attachment_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attendance_log" ADD CONSTRAINT "attendance_log_placementId_placement_id_fk" FOREIGN KEY ("placementId") REFERENCES "public"."placement"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attendance_log" ADD CONSTRAINT "attendance_log_verifiedByMentorId_mentor_profile_id_fk" FOREIGN KEY ("verifiedByMentorId") REFERENCES "public"."mentor_profile"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "calendar_event" ADD CONSTRAINT "calendar_event_placementId_placement_id_fk" FOREIGN KEY ("placementId") REFERENCES "public"."placement"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "calendar_event" ADD CONSTRAINT "calendar_event_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "final_report" ADD CONSTRAINT "final_report_placementId_placement_id_fk" FOREIGN KEY ("placementId") REFERENCES "public"."placement"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "final_report" ADD CONSTRAINT "final_report_approvedByMentorId_mentor_profile_id_fk" FOREIGN KEY ("approvedByMentorId") REFERENCES "public"."mentor_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "final_report_score" ADD CONSTRAINT "final_report_score_finalReportId_final_report_id_fk" FOREIGN KEY ("finalReportId") REFERENCES "public"."final_report"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "final_report_score" ADD CONSTRAINT "final_report_score_competencyTemplateId_competency_template_id_fk" FOREIGN KEY ("competencyTemplateId") REFERENCES "public"."competency_template"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mentor_profile" ADD CONSTRAINT "mentor_profile_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mentor_profile" ADD CONSTRAINT "mentor_profile_companyId_company_id_fk" FOREIGN KEY ("companyId") REFERENCES "public"."company"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification" ADD CONSTRAINT "notification_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "placement" ADD CONSTRAINT "placement_studentId_student_profile_id_fk" FOREIGN KEY ("studentId") REFERENCES "public"."student_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "placement" ADD CONSTRAINT "placement_mentorId_mentor_profile_id_fk" FOREIGN KEY ("mentorId") REFERENCES "public"."mentor_profile"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "placement" ADD CONSTRAINT "placement_companyId_company_id_fk" FOREIGN KEY ("companyId") REFERENCES "public"."company"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "placement" ADD CONSTRAINT "placement_programId_program_id_fk" FOREIGN KEY ("programId") REFERENCES "public"."program"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report" ADD CONSTRAINT "report_placementId_placement_id_fk" FOREIGN KEY ("placementId") REFERENCES "public"."placement"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "report" ADD CONSTRAINT "report_reviewedByMentorId_mentor_profile_id_fk" FOREIGN KEY ("reviewedByMentorId") REFERENCES "public"."mentor_profile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_impersonated_by_user_id_fk" FOREIGN KEY ("impersonated_by") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_profile" ADD CONSTRAINT "student_profile_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_placementId_placement_id_fk" FOREIGN KEY ("placementId") REFERENCES "public"."placement"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_checklist_item" ADD CONSTRAINT "task_checklist_item_taskId_task_id_fk" FOREIGN KEY ("taskId") REFERENCES "public"."task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_competency_impact" ADD CONSTRAINT "task_competency_impact_taskId_task_id_fk" FOREIGN KEY ("taskId") REFERENCES "public"."task"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_competency_impact" ADD CONSTRAINT "task_competency_impact_competencyTemplateId_competency_template_id_fk" FOREIGN KEY ("competencyTemplateId") REFERENCES "public"."competency_template"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attachment_owner_idx" ON "attachment" USING btree ("owner_type","ownerId");--> statement-breakpoint
CREATE UNIQUE INDEX "attendance_unique_per_day" ON "attendance_log" USING btree ("placementId","date");--> statement-breakpoint
CREATE INDEX "attendance_status_idx" ON "attendance_log" USING btree ("status");--> statement-breakpoint
CREATE INDEX "company_name_idx" ON "company" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "mentor_user_unique" ON "mentor_profile" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "mentor_company_idx" ON "mentor_profile" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "notification_user_idx" ON "notification" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "notification_read_idx" ON "notification" USING btree ("isRead");--> statement-breakpoint
CREATE INDEX "placement_student_idx" ON "placement" USING btree ("studentId");--> statement-breakpoint
CREATE INDEX "placement_status_idx" ON "placement" USING btree ("status");--> statement-breakpoint
CREATE INDEX "report_type_idx" ON "report" USING btree ("type");--> statement-breakpoint
CREATE INDEX "report_placement_idx" ON "report" USING btree ("placementId");--> statement-breakpoint
CREATE UNIQUE INDEX "student_user_unique" ON "student_profile" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "task_placement_status_idx" ON "task" USING btree ("placementId","status");--> statement-breakpoint
CREATE INDEX "task_due_date_idx" ON "task" USING btree ("dueDate");--> statement-breakpoint
CREATE INDEX "checklist_task_idx" ON "task_checklist_item" USING btree ("taskId");